# Generated by Django 3.2.3 on 2021-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('app_date', models.DateTimeField()),
                ('doctor_name', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=100)),
                ('fees', models.PositiveIntegerField()),
                ('is_pay', models.BooleanField(default=False)),
                ('appointment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('doctor_name', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('prescription', models.CharField(max_length=1024)),
                ('days', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
