# Generated by Django 3.2.3 on 2021-05-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
