# Generated by Django 3.2.3 on 2021-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_appointment_app_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fees',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
