# Generated by Django 3.2.3 on 2021-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_appointment_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='book_date',
            field=models.DateField(auto_now=True),
        ),
    ]
