# Generated by Django 3.2.3 on 2021-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_appointment_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
